#!/bin/bash

#-----------------------------------------------------------------------------
_EXPORT_VLIST=()

function def
{
    _EXPORT_VLIST=$(_def ${#_EXPORT_VLIST[@]} ${_EXPORT_VLIST[@]} $*)
}

function undef
{
    _EXPORT_VLIST=$(_undef ${#_EXPORT_VLIST[@]} ${_EXPORT_VLIST[@]} $*)
}
#-----------------------------------------------------------------------------

def _TPLG_LIST
function load_tplg #$1: tplgFile
{
    local tplgFile=$1
    if [[ -f $tplgFile ]]; then
        echo ""
    fi
}

_TPLG_LIST=(123 4 5 6 7  8 9 11)
